messages:
  no_permissions: "&cYou don't have permission to use this KillEffect."
  effect_set: "&aYou have selected the KillEffect: &e%effect%"
  effect_already_set: "&eYou have already selected this KillEffect!"
  config_reloaded: "&aConfiguration successfully reloaded!"
  gui_title: "&6Select your KillEffect"
  effect_not_found: "&cKillEffect not found!"
  miss_usage: "&cUse this command &e/kt reload|set|test"
  only_players: "&cOnly players can execute this command!"
  effect_executed: "&aKillEffect executed: &e%effect%"
  invalid_potion: "&cInvalid or missing configured potion: no potion applied."
  potion_set: "&aYou received: &e%potion% %amplifier%"

resource_pack:
  url: "https://download.mc-packs.net/pack/d5889f788003340479e3f767852eddee152ee544.zip"
  sha1: "d5889f788003340479e3f767852eddee152ee544"
  sounds:
    bow-hit:
      name: "kt.hs1"

effects:
  fire:
    name: "&cFire"
    description: "&cBurn &7your enemies with fire"
  lightning:
    name: "&eLightning"
    description: "&bSummon a &elightning bolt &bon your target"
  explosion:
    name: "&4Explosion"
    description: "&4Boom! &7A visual explosion effect"
  hearts:
    name: "&dHearts"
    description: "&dLove hearts &7when you kill"
  notes:
    name: "&aNotes"
    description: "&aMusical effect &ein the rhythm of death"
  cloud:
    name: "&fCloud"
    description: "&fMysterious &7and haunting fog"
  smoke:
    name: "&8Smoke"
    description: "&8Smoke &7and shadows in the air"
  totem:
    name: "&6Totem"
    description: "&6Epic &eparticles &6of the totem"
  end:
    name: "&5End"
    description: "&5Creepy &dEnderman &5effect"
  pigstep:
    name: "&dPigStep"
    description: "&dPig &bStep &eeffect"
  warden:
    name: "&3Warden"
    description: "&3Warden &eeffect"
  glowmissile:
    name: "&bGlowMissile"
    description: "&bGlow missile &7effect"

  sniper:
    name: "&cSniper"
    description:
      - "&7Long Mortal Shot"
      - "&8Only kill with bow"

  enchantcolumn:
    name: "&rEnchant&7Column"
    description: "&rEnchant&7Column &eExplosion!"
    effectexplosion:
      type: REGENERATION
      amplifier: 2
      duration: 10

  fireworks:
    name: "&bFireworks"
    description: "&cFire &fworks &7and explosions"
